### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by zekesonxx** [blt4linux/blt4l#27]
Hi, so I was trying to make a AUR package for this, when I came across the fact that you don't appear to have any license specified anywhere.

As a result, your repo currently exists in a very grey legal area. Please to fix, thanks.

**Comment by LeonardKoenig** [comment]
You're right, I think we all totally forgot about this. BLT4WIN uses MIT. One could also of course go with something more strict like GPL as sadly some people in the Payday 2 community are rather closed-source-friendly (looking at you, HoxHud) and kind of hindering collaboration. But in the end I think it's up to @RomanHargrave to decide.

**Comment by zekesonxx** [comment]
I'd also vote for [GPL](https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)); but I don't have any code in the repo so I can't say much.

subhook is [2-clause BSD](https://tldrlegal.com/license/bsd-2-clause-license-(freebsd)) so you're not stuck with anything from that.

**Comment by RomanHargrave** [comment]
OK. So, first of all, we will need @JamesWilko to decide on a license for the shared code (all the LUA was written by himself and other BLT4Win contributors). After that, we will need to reconcile it with our choice of license. I would like to license BLT4Linux under a license that _requires_ downstream improvements to come back upstream, so GPL3 is pretty enticing.

As for packaging, if you want to go ahead and package, I would suggest that you list the package as proprietary until we can get James to decide on a license for the LUA; or, if you choose to download the LUA instead of packaging it (which you should do, since the loader auto-updates the LUA), list it as proprietary-open-source with copyright belonging to myself and the contributers listed in the README until we can decide on a license (at which point you may change it).

Furthermore, since I assume AUR installs packages system-wide rather than user-local, we will need to modify the loader to auto-install the LUA for the hook if it can't find it. By saying you are going to package it for the AUR, I assume that you have already made the requisite changes? If so, we will need to have them upstream if you don't mind.

Also, please note that there is a bit of a caveat to the dynamic linker -- you cannot have spaces in the LD_PRELOAD specification (spaces are used as separators). Be sure to install the shared object in such a path.

**Comment by RomanHargrave** [comment]
@zekesonxx you are free to continue packaging under the terms enclosed in `LICENSE` now.
