### ISSUE TITLE
Rearchitect Installer/Builder architecture

### ISSUE THREAD

**Issue by RomanHargrave** [blt4linux/blt4l#37]
Given recent issues brought up around installer compatibility, I feel that it may be beneficial to rewrite the installer as a multipart perl script (perl, as it's most likely to already be installed on most Linux systems, almost 99% certain on Debian and Ubuntu/SteamOS).

Currently, the script I use to automate builds in the different distribution chroots is a modification of the shell script installer. If we moved the installer logic to a central place, the differences between the installer and chroot builder would be miniscule and any changes to the central installer logic would affect both, which means less maintainence. 

Additionally, writing in a more flexible language would open up the ability to parse _and_ modify VDF files, therefore allowing _perfect_ location of the payday install location, _and_ set the launch parameters, therefore making installation-to-launch fully transparent to the user.

**Comment by awilliamson** [comment]
There is an argument to be said to keep the installer in a contributor-friendly language. Where all users and contributors can understand the script easily. The install script is written in the de-facto language for install scripts. Just because there's discussion on the correct way to do something, does not imply that the delivery is flawed. You will likely have similar if not more issues re-implementing an install script.

**Comment by RomanHargrave** [comment]
True, this is just a suggestion for consideration.
