### ISSUE TITLE
symbol lookup error

### ISSUE THREAD

**Issue by share234** [blt4linux/blt4l#58]
symbol lookup error: ./libblt_loader.so: undefined symbol: CRYPTO_num_locks
 
Game runs as normal without it.

ldd:
`	linux-vdso.so.1 (0x00007ffdde438000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f26927c6000)
	libcurl-gnutls.so.4 => /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4 (0x00007f2692546000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f2692326000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f2691f9e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2691c96000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f2691a7e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f26916de000)
	/lib64/ld-linux-x86-64.so.2 (0x0000556f8cd8e000)
	libnghttp2.so.14 => /usr/lib/x86_64-linux-gnu/libnghttp2.so.14 (0x00007f26914b6000)
	libidn.so.11 => /lib/x86_64-linux-gnu/libidn.so.11 (0x00007f269127e000)
	librtmp.so.1 => /usr/lib/x86_64-linux-gnu/librtmp.so.1 (0x00007f269105e000)
	libssh2.so.1 => /usr/lib/x86_64-linux-gnu/libssh2.so.1 (0x00007f2690e2e000)
	libnettle.so.6 => /usr/lib/x86_64-linux-gnu/libnettle.so.6 (0x00007f2690bf6000)
	libgnutls.so.30 => /usr/lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007f2690856000)
	libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f2690606000)
	libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f2690326000)
	libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f26900ee000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f268fee6000)
	liblber-2.4.so.2 => /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2 (0x00007f268fcd6000)
	libldap_r-2.4.so.2 => /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2 (0x00007f268fa7e000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f268f85e000)
	libhogweed.so.4 => /usr/lib/x86_64-linux-gnu/libhogweed.so.4 (0x00007f268f626000)
	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f268f39e000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f268f08e000)
	libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f268ee26000)
	libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f268ec0e000)
	libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f268e9fe000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f268e7f6000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f268e5de000)
	libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007f268e3be000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f268e1a6000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f268df96000)
`

**Comment by RomanHargrave** [comment]
Build BLT with cURL-openssl instead of GNUTLS

---- On Sat, 10 Jun 2017 11:42:38 -0700 notifications@github.com wrote ----

symbol lookup error: ./libblt_loader.so: undefined symbol: CRYPTO_num_locks

Game runs as normal without it.

ldd:
linux-vdso.so.1 (0x00007ffdde438000) libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f26927c6000) libcurl-gnutls.so.4 => /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4 (0x00007f2692546000) libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f2692326000) libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f2691f9e000) libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2691c96000) libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f2691a7e000) libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f26916de000) /lib64/ld-linux-x86-64.so.2 (0x0000556f8cd8e000) libnghttp2.so.14 => /usr/lib/x86_64-linux-gnu/libnghttp2.so.14 (0x00007f26914b6000) libidn.so.11 => /lib/x86_64-linux-gnu/libidn.so.11 (0x00007f269127e000) librtmp.so.1 => /usr/lib/x86_64-linux-gnu/librtmp.so.1 (0x00007f269105e000) libssh2.so.1 => /usr/lib/x86_64-linux-gnu/libssh2.so.1 (0x00007f2690e2e000) libnettle.so.6 => /usr/lib/x86_64-linux-gnu/libnettle.so.6 (0x00007f2690bf6000) libgnutls.so.30 => /usr/lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007f2690856000) libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f2690606000) libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f2690326000) libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f26900ee000) libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f268fee6000) liblber-2.4.so.2 => /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2 (0x00007f268fcd6000) libldap_r-2.4.so.2 => /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2 (0x00007f268fa7e000) libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f268f85e000) libhogweed.so.4 => /usr/lib/x86_64-linux-gnu/libhogweed.so.4 (0x00007f268f626000) libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f268f39e000) libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f268f08e000) libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f268ee26000) libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f268ec0e000) libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f268e9fe000) libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f268e7f6000) libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f268e5de000) libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007f268e3be000) libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f268e1a6000) libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f268df96000)

**Comment by share234** [comment]
Ok, i found out its to do with the latest releases you have provided. As i don't know how to Build them myself i just tried a version back and that seemed to work fine.

**Comment by RomanHargrave** [comment]
yeah, sorry about that. 

try the steamrt release

**Comment by share234** [comment]
I've got it working perfectly now just with version 1.3 instead of 1.3-r1-1
