### ISSUE TITLE
libblt_loader.so: undefined symbol: lua_call

### ISSUE THREAD

**Issue by thankjura** [blt4linux/blt4l#76]
libblt_loader.so not loaded after latest game update

>$ export LD_PRELOAD="libblt_loader.so"
>$ ./payday2_release                                                                             
> dlHandle = 0x7fd9cc5cc110
> 09:58:23 PM Info: finding lua functions
> 09:58:23 PM Info: installing hooks
> szCmd: /bin/sh -c '"/home/GrandMaster/.local/share/Steam/steam.sh" "steam://run/218620"' &
> sh: symbol lookup error: /home/GrandMaster/Development/games/blt4l/installer_build/libblt_loader.so: 
undefined symbol: lua_call

**Comment by RomanHargrave** [comment]
It's because you're launching PAYDAY without the requisite steam environment, so it tells steam to launch it.

In order to launch PAYDAY, steam spawns a process, which blt tries to hook (it doesn't really have control over what it hooks, since the linker just inserts it). This process is missing PAYDAY's symbols, since it's not PAYDAY.

BLT expects that any process the linker inserts it in to will be PAYDAY. This is fine for proper operation since PAYDAY doesn't spawn any children when run correctly.

**Comment by thankjura** [comment]
http://i.imgur.com/pyEKMrB.png
It also stopped working after the last updates of the game.
I run payday 2 from steam and mods not loaded

**Comment by thankjura** [comment]
I close steam and reinstall blt4l, and problem disappeared. If steam running - .steam/steam/userdata/114149083/config/localconfig.vdf file not modified
