### ISSUE TITLE
Missing menu elements (mainly Lua mods), only one mod show up in "Mod Options"

### ISSUE THREAD

**Issue by swoodmood** [blt4linux/blt4l#98]
I'll let the images speak for themselves. I've tried installing every single way, but this is borderline hopeless.

![image](https://user-images.githubusercontent.com/18504677/32703265-6cd01720-c7f3-11e7-8802-3d8ae9644940.png)
![screenshot_2017-11-12_21-52-13](https://user-images.githubusercontent.com/18504677/32703293-f4acdec6-c7f3-11e7-8485-a71b558097ab.png)
![screenshot_2017-11-12_21-52-55](https://user-images.githubusercontent.com/18504677/32703294-f5f1ebb4-c7f3-11e7-8216-c76f9780e928.png)

As you can see I have plenty of mods installed, but restoration simply doesn't work and I can only customize one. What's going on here? I'm using Xubuntu 16.04.

**Comment by ZNixian** [comment]
Could you go into your mods/logs folder, and upload the latest log file.

**Comment by swoodmood** [comment]
[2017_11_12_log.txt](https://github.com/blt4linux/blt4l/files/1465141/2017_11_12_log.txt)

Here you go, @ZNixian

**Comment by ZNixian** [comment]
There's quite a lot of errors in that log.

Three big issues I see:

- BeardLib uses functions missing from the GNU+Linux version of PAYDAY 2. For now, until they fix that issue, iirc this fixed it: http://download.paydaymods.com/download/latest/556
- RestorationMod isn't working for some reason. If it needs BeardLib, try fixing that first.
(`Error: mods/RestorationMod/Core.lua:2: attempt to index global 'RestorationCore' (a nil value)`)
- WolfHUD is having some issues. Download the latest version from [GitHub](https://github.com/Kamikaze94/WolfHUD).

The BeardLib issue is from #96, the others are due to the mods themselves and aren't really BLT's fault. I'll close the issue, however I'll still help if the above steps don't fix it.

PS: Delete your log before launching if you're going to upload it, so there's only the most recent launch in it.

**Comment by swoodmood** [comment]
Seems like the issue was Restoration Mod, but one thing still bothers me. Take a look at this image from a tutorial regarding BLT4Linux.

![image](https://user-images.githubusercontent.com/18504677/32704223-06564e9c-c802-11e7-829b-85f2869907f1.png)

Where did the "Lua Mods" tab go?

**Comment by ZNixian** [comment]
A while back, PAYDAY 2 changed from using the 'Lua 5.1' interpreter to the 'LuaJIT' just-in-time compiler. They both run the same Lua code the same way, but LuaJIT is upto a few hundred times faster.

However, this change broke the windows version of BLT - every time you opened the game, it would crash IIRC. So they had to rewrite the BLT .dll hook - and while they were at it, they also rewrote the Lua part of BLT, which is responsible for the BLT-related menus.

None of this affected BLT4L too much, as our hook kept working despite the change to LuaJIT. After awhile, BLT4L changed to being bundled with the new version of the Lua part of BLT, as new mods were starting to require it.
